### ISSUE TITLE
Slow Performance on Smooth Scroll - Animation Stuttering

### ISSUE THREAD

**Issue by Reza-Eskandari** [locomotivemtl/locomotive-scroll#181]
Hello 👋

**Describe the bug**
Even though I've incorporated the `data-scroll-section`, I've noticed when I enable smooth scroll the scroll behavior becomes very slow and choppy and my CSS animation stutter heavily. It becomes a lot more noticeable on elements that have different `data-scroll-speed` for the parallax effect (in my case is a bunch of images in a grid).

**To Reproduce**
I can't share my code here but I noticed the same frame drops on the [locomotive.ca homepage](https://locomotive.ca/en). But at the same time when I visit this [codepen example](https://codepen.io/ebinabo/pen/WNwjEaL), everything is buttery smooth! The reason I chose the locomotive.ca website is that my homepage shares a lot of similarities (like using Swiper Js, etc). Regardless I've forked the codepen example mentioned above surprisingly it's buttery smooth literally everywhere except the section I added. Here the link to the forked version: https://codepen.io/itsprorez/pen/xxOgRoO . I've noticed the choppiness mainly when the scroll travels a short distance and when it's easing at the end.

**Expected behavior**
I really want to achieve the same performance as this [codepen example](https://codepen.io/ebinabo/pen/WNwjEaL) but I have no idea what I'm doing wrong!

**Screenshots**

- Here's a screenshot of the [locomotive.ca website](https://locomotive.ca/en) recorded starting at the top of the website and ended at the bottom. https://share.getcloudapp.com/v1uxQln8
- Here's a screen recording of the choppiness behavior in the [locomotive.ca](https://locomotive.ca/en) : https://share.getcloudapp.com/NQu1jbGq
- Here's a screen recording of the choppiness behavior in my website: https://share.getcloudapp.com/NQu1jd1K

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 86.0.4240.111 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Everything works fine on smartphones. I've noticed the problem only on desktop browsers.

Thank you 👊

**Comment by ehsan-shv** [comment]
do you find better way to fix this problem?

**Comment by dngraphisme** [comment]
Hello @Reza-Eskandari, i have a similar problem :(

On a Wordpress site for one of my clients. I have update Locomotive in version 4 but since the homepage is really slow to scroll on chrome.

No problem, however, on Firefox dev or safari ...

Could someone help us ?

**Comment by isotropicdesign** [comment]
Some issue on WordPress. Any developments regarding this issue? My smooth scroll is super choppy.

**Comment by ehsan-shv** [comment]
no better way to fix this peoblem?

**Comment by BlazeIsClone** [comment]
Hey guys so I've ran into the same problem, everything worked fine except when the scrolling came to an end the text will start loosing FPS and becomes laggy (like a shivering effect). I've tried many different things although one thing fixed it for me, so check this out if you are facing something similar to what I have experienced. 

` will-change: transform, opacity;` 

**Don't apply will-change to too many elements**  (that's the first things said in the docs)

[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)

**Comment by SoulDesignerTom** [comment]
I've noticed that on my website this laggy issue was made by having a very complex SVG image.
Even if it was in a <img> tag - changed to .png and everything works perfectly smoothly.

Try to determin what is causing this lagging - you can remove section by section and aim for the problem.

**Comment by MichaelGei** [comment]
> I've noticed that on my website this laggy issue was made by having a very complex SVG image.
Even if it was in a  tag - changed to .png and everything works perfectly smoothly.

Try to determin what is causing this lagging - you can remove section by section and aim for the problem.

Thx!  Ran Into the same issue as yours and I just fixed it by replacing complex svg img with png...lol

**Comment by paul-coupl** [comment]
Placing `will-change: 'transform'` in the styles of `data-scroll-section` magically enhanced the performance 👍

**Comment by maviarebo** [comment]
Gsap scrollsmoother pade is shaking while scrolling issue

- I was scrolling a website, and I noticed that an element's border is shaking and behaving oddly. I tried using 'will-change: transform,' but it didn't fix the issue.

Hey, can anyone lend a hand with fixing this problem?
