### ISSUE TITLE
Position fixed element still scroll with the page when using locomotive scroll

### ISSUE THREAD

**Issue by Emmanx** [locomotivemtl/locomotive-scroll#282]
Hello 👋

**Describe the bug**
Position fixed element still scroll with the page when using locomotive scroll

**To Reproduce**
1. Add locomotive scroll
2. Make an element on the page position fixed.
3. Scroll down on the page to see if the element is fixed

Thank you 👊

**Comment by apsolut** [comment]
I think this isnt a bug, because locomotive uses `translate` to move not body normal scroll - to sick elements you need to use sticky,
`   <div class="your-fixed-element" data-scroll data-scroll-sticky data-scroll-target="#YOURID">`

**Comment by jeronimus23** [comment]
> I think this isnt a bug, because locomotive uses `translate` to move not body normal scroll - to sick elements you need to use sticky,
> ` <div class="your-fixed-element" data-scroll data-scroll-sticky data-scroll-target="#YOURID">`

Not working

**Comment by Iraklikandelaki** [comment]
> > I think this isnt a bug, because locomotive uses `translate` to move not body normal scroll - to sick elements you need to use sticky,
> > ` <div class="your-fixed-element" data-scroll data-scroll-sticky data-scroll-target="#YOURID">`
> 
> Not working

You need to set the target div for the div that should be fixed, since the Locomotive doesn't rely on native scroll and literally scrolls in a custom div. That's why `position: fixed` will not work.

**Comment by ZakaryaNoori** [comment]
Hello,
I am having the same issue where my fixed element still scrolls with page scroll I am using gsap nuxt module how do I set scroll target on my elements?

**Comment by vsnthdev** [comment]
I'd also like to know it

**Comment by obinasBaba** [comment]
[Here](https://webdesign.tutsplus.com/tutorials/scrolling-website-with-locomotive-scroll-tailwind-css--cms-36943) is a blog which explains the features of locomotive. Generally when you set `position: fixed` on an element, it is fixed, it's not that it is not fixed but when you start to scroll, `locomotive` will translate the container in `y` direction, hence all its nested items, and that is how `locomotive` simulate the scrolling effect. You can try: 

- Take the fixed element out of locomotive container, You can use [React Portal](https://reactjs.org/docs/portals.html) 

- Try the locomotive way, Keep in mind: 
  - You need to set `data-scroll` so that locomotive detects it,  `data-scroll-sticky` to set it fixed, `data-scroll-target` to enable locomotive to determine the fixed element’s initial and final sticky positions, 
    - When the _target_ element `top` touch the top of the `viewport`, the fixed element will start to stick,  
    - When the _target_ `bottom` touch the top of the `viewport`, the fixed element will lose its stickness,

**Comment by HamidDev22** [comment]
Hello all 👋
every element in **"data-scroll-container"** get scrolled along the page no matter what position it has so, to make a fixed position element simply place it somewhere out of the **"data-scroll-container"**

`<body>
	
    <button id="menu-button" class="menu-button">
         // Fixed position button
    </button>
	<div class="scrollContainer" data-scroll-container>
		// Something
	</div>
</body>`

**Comment by Lavitr** [comment]
I have encountered the same issue and the solution was to set `data-scroll-target` to outer `data-scroll-container`.
`<div data-scroll-container id="scroll-container">
...
  <div class="fixed" data-scroll data-scroll-sticky data-scroll-target="#scroll-container">
    // Fixed content`

**Comment by iamrobert** [comment]
I was having issues with a fixed menu. I switched my CSS from `position: fixed`  to `position: sticky,` and locomotive handled it well.

**Comment by Tammura** [comment]
I think you have to add `position: sticky`, so it will be:
 `<div class="sticky" data-scroll data-scroll-sticky data-scroll-target="#scroll-container">`

**Comment by fito1991** [comment]
> I have encountered the same issue and the solution was to set `data-scroll-target` to outer `data-scroll-container`.
> 
> ```
> <div data-scroll-container id="scroll-container">
>   ...
>   <div class="fixed" data-scroll data-scroll-sticky data-scroll-target="#scroll-container">
>     // Fixed content
> ```

not working

**Comment by muhamedkarajic** [comment]
I would also like to know this my goal is to move the position fixed element on mouse movement. I can't acchive it so far.

**Comment by HangLimbu995** [comment]
> > > I think this isnt a bug, because locomotive uses `translate` to move not body normal scroll - to sick elements you need to use sticky,
> > > ` <div class="your-fixed-element" data-scroll data-scroll-sticky data-scroll-target="#YOURID">`
> > 
> > 
> > Not working
> 
> You need to set the target div for the div that should be fixed, since the Locomotive doesn't rely on native scroll and literally scrolls in a custom div. That's why `position: fixed` will not work.

well in data-scroll-target='id' . id should be from its parent element with which you want to put it relative to. And also give id to its parent element and it will be done.
I did the same and it worked fine.
