### ISSUE TITLE
Having a class like active on section in viewport only!!!

### ISSUE THREAD

**Issue by nashvinxtn** [locomotivemtl/locomotive-scroll#91]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

---
_@locomotivemtl feedback below_
## Current progress for this issue

- [X] Append `data-scroll-section-inview` when a section is "visible"
- [ ] Add ability to define the offset for when a section is considered "visible". Around here: https://github.com/locomotivemtl/locomotive-scroll/blob/48e90230d001f41a27758bc95afe2ea8199659cf/src/scripts/Smooth.js#L427-L428 Maybe rename `offset` & `limit` to `start` & `end` for clarity? 🤔

_Please keep in mind we work on this library when we can. As a web agency with clients paying for their projects, we have priorities. Since those are enhancements and as long as we don't need them in our own projects, they are not top priority._

**Comment by adamcoulombe** [comment]
You can do this. Just add `data-scroll` to your `data-scroll-section` and use the `in-view` class.
```
<div data-scroll data-scroll-section>
    ...
</div>
```

**Comment by Jerek0** [comment]
Hi, please take the time to describe your issue in the description next time. 😉 

Resolved by eef359bd4fdc28e7cba73185b696d8f4f6178afc. Inview sections will have the attribute `data-scroll-section-inview`

@adamcoulombe unfortunately that won't work. As soon as you use sections, only the `data-scroll` elements inside those sections will be taken care of.

**Comment by nashvinxtn** [comment]
@Jerek0 FIrst of all thanks for the plugin, its really great. Ill make sure to describe any issue in the description next time. I have updated the lib on my local and that work. 
But one thing its still not precise as the attribute sometimes appear on 2 sections event if the other section before or after is already out of viewport. Can something be done?

**Comment by Jerek0** [comment]
## Current progress for this issue

- [X] Append `data-scroll-section-inview` when a section is "visible"
- [ ] Add ability to define the offset for when a section is considered "visible". Around here: https://github.com/locomotivemtl/locomotive-scroll/blob/48e90230d001f41a27758bc95afe2ea8199659cf/src/scripts/Smooth.js#L427-L428 Maybe rename `offset` & `limit` to `start` & `end` for clarity? 🤔

_Please keep in mind we work on this library when we can. As a web agency with clients paying for their projects, we have priorities. Since those are enhancements and as long as we don't need them in our own projects, they are not top priority._

----

In the meantime if you do not want any offset at all, I suggest you fork this library and play with the `window.innerHeight` factor on lines quoted above. Probably something like this
```JS
let offset = section.getBoundingClientRect().top - window.innerHeight - getTranslate(section).y;
let limit = offset + section.getBoundingClientRect().height + window.innerHeight;
```

**Comment by podrivo** [comment]
`data-scroll-section-inview` is working great for me!
I can use this to manipulate fixed elements in the page. Thanks!

**Comment by PierreMouchan** [comment]
Thanks for answering this issue, can someone please provide me a full example on how to manipulate sticky element on the page with ```data-scroll-section-inview``` ?
thanks
